services:
  rev:
    build: .
    command: sh -c 'python /app/main.py --log-level $$LOG_LEVEL --email $$EMAIL --password $$PASSWORD'
    volumes:
      - .:/app
    environment:
      LOG_LEVEL: INFO
      PYTHONUNBUFFERED: "1"
    env_file: "login.env"
