services:
  xml:
    # https://gnome.pages.gitlab.gnome.org/libxml2/xmllint.html
    build:
      context: .
      dockerfile: ./Dockerfile.xmllint
    command:
      - --noout
      - --schema
      - /schema/addon.xsd
      - /src/plugin.video.dropout.tv/addon.xml
    volumes:
      - ../../src:/src
      - ./schema:/schema
