name: Create ZIP
run-name: Zip, zip, zipping on repo's '${{ github.ref }}'
on: [push]
jobs:
  Zip:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin.video.dropout.tv-0.1.0-alpha
          path: ${{ github.workspace }}/src
